using System;
using System.Runtime.Serialization;

namespace System {
    /// <summary>
    /// <para>EndUserGeneratedException classes represent Exceptions that are generated by the End User trying to do something that
    /// is by design not acceptable or possible for the program to handle.</para>
    /// <para>ObjectNotFoundException means that the user is trying to access something that doesn't exist.</para>
    /// </summary>
    [Serializable]
    public class FailedExpectationException : EndUserGeneratedException {

        public FailedExpectationException(string message) : base(417, message) {
        }

        public FailedExpectationException(string message, Exception innerException) : base(417, message, innerException) {
        }
        
        protected FailedExpectationException(SerializationInfo info, StreamingContext context) : base(417, info, context) {
        }
    }
}