using System;
using System.Runtime.Serialization;

namespace System {
    /// <summary>
    /// <para>EndUserGeneratedException classes represent Exceptions that are generated by the End User trying to do something that
    /// is by design not acceptable or possible for the program to handle.</para>
    /// <para>ObjectNotFoundException means that the user is trying to access something that doesn't exist.</para>
    /// </summary>
    [Serializable]
    public sealed class ForbiddenAccessException : EndUserGeneratedException {

        public ForbiddenAccessException(string message) : base(403, message) {
        }

        public ForbiddenAccessException(string message, Exception innerException) : base(403, message, innerException) {
        }
        
        protected ForbiddenAccessException(SerializationInfo info, StreamingContext context) : base(403, info, context) {
        }
    }
}