using System;
using System.Runtime.Serialization;

namespace System {
    /// <summary>
    /// <para>EndUserGeneratedException classes represent Exceptions that are generated by the End User trying to do something that
    /// is by design not acceptable or possible for the program to handle.</para>
    /// <para>ObjectNotFoundException means that the user is trying to access something that doesn't exist.</para>
    /// </summary>
    [Serializable]
    public class ObjectNotFoundException : EndUserGeneratedException {

        public ObjectNotFoundException(string message) : base(404, message) {
        }

        public ObjectNotFoundException(string message, Exception innerException) : base(404, message, innerException) {
        }
        
        protected ObjectNotFoundException(SerializationInfo info, StreamingContext context) : base(404, info, context) {
        }
    }
}